# Generated by Django 5.0.3 on 2024-03-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_facebook_link_profile_instagram_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_available_for_emergencies',
            field=models.BooleanField(default=False),
        ),
    ]
