# Generated by Django 5.0.3 on 2024-03-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_is_available_for_emergencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_available_for_emergencies',
            field=models.BooleanField(default=True),
        ),
    ]
