# Generated by Django 5.0.3 on 2024-03-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='note',
            field=models.TextField(default='Nothing'),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='note',
            field=models.TextField(default='Nothing'),
        ),
    ]
