# Generated by Django 5.0.3 on 2024-03-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0002_appointment_note_appointmentrequest_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
